---
apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: cloud-httpd

  name: cloud-httpd
  namespace: ingress-web-test

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: cloud
      k8s.kuboard.cn/name: cloud-httpd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: cloud
        k8s.kuboard.cn/name: cloud-httpd
    spec:
      containers:
        - image: httpd
          imagePullPolicy: Always
          name: httpd
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30


---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.kuboard.cn/workload: cloud-httpd

  labels:
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: cloud-httpd
  name: cloud-httpd
  namespace: ingress-web-test

spec:
  ports:
    - name: h2tji5
      port: 8089
      protocol: TCP
      targetPort: 80
  selector:
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: cloud-httpd
  sessionAffinity: None
  type: ClusterIP

