apiVersion: v1
kind: PodTemplate
metadata:
  name: hjl-nginx
template:
  metadata:
    labels:
      name: nginx
  spec:
    containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
