apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-web-deplotment

spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: my-web

    spec:
      containers:
      - name: my-web
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
