apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: lnmp
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/nfs/mysql
    server: 192.168.1.40
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-one
  namespace: lnmp
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/nfs/data
    server: 192.168.1.40
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-two
  namespace: lnmp
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/nfs/data
    server: 192.168.1.40
