---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-nfs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: www                           # 数据卷名称
          mountPath: /usr/share/nginx/html    # 容器数据卷挂载路径
        ports:
        - containerPort: 80
      volumes:
      - name: www                             # 数据卷名称两边需要相同
        nfs:
          server: 192.168.1.40          # nfs服务器地址
          path: /data/nfs/nginx         # 服务端共享路径

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
