# create 3 copies of container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment-nginx-deployment
  labels:
    app: Deployment-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Deployment-nginx
  template:
    metadata:
      labels:
        app: Deployment-nginx
    spec:
      containers:
      - name: Deployment-nginx
        image: Deployment-nginx:1.7.9
        ports:
        - containerPort: 80

