apiVersion: v1
kind: ReplicationController
metadata:
  name: my-web-v1

spec:
  replicas: 1
  selector:
    app: my-web
    version: v1
  template:
    metadata:
      labels:
        app: my-web
        version: v1

    spec:
      containers:
      - name: my-web
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
