---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.kuboard.cn/workload: hu-nginx
  labels:
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: hu-nginx

  name: hu-nginx
  namespace: default

spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: hu-nginx
  type: ClusterIP